esphome:
  name: zebus
  friendly_name: Zebus Verwarming

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_iot_ssid
  password: !secret wifi_iot_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zebus Fallback Hotspot"
    password: !secret wifi_ap_fallback_password

captive_portal:

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components

ebus:
  master_address: 0x00
  history_queue_size: 32
  command_queue_size: 16
  poll_interval: "15s"
  uart:
    num: 1
    tx_pin: 33
    rx_pin: 32

sensor:
  - platform: ebus
    sensors:
      - name: "Water Pressure"
        id: zebus_water_pressure
        message:
          destination: 0x03
          command: 0xb509
          payload: [0x0d, 0x02, 0x00]
          decode:
            position: 0
            bytes: 2
            divider: 1000.0
        device_class: "pressure"
        unit_of_measurement: bar
        state_class: "measurement"
        accuracy_decimals: 3
        internal: false
        filters:
          - clamp:
              min_value: 0
              max_value: 4
              ignore_out_of_range: true
          - median:
              window_size: 5
              send_every: 3
              send_first_at: 3
      - name: "Flow Temperature"
        id: zebus_flow_temperature
        device_class: "temperature"
        unit_of_measurement: "째C"
        state_class: "measurement"
        accuracy_decimals: 1
        internal: false
        message:
          command: 0xb511
          payload: [0x01]
          decode:
            position: 0
            bytes: 1
            divider: 2.0
        filters:
          - median:
              window_size: 5
              send_every: 3
              send_first_at: 3
      - name: "Return Temperature"
        id: zebus_return_temperature
        device_class: "temperature"
        unit_of_measurement: "째C"
        state_class: "measurement"
        accuracy_decimals: 1
        internal: false
        message:
          command: 0xb511
          payload: [0x01]
          decode:
            position: 1
            bytes: 1
            divider: 2.0
        filters:
          - median:
              window_size: 5
              send_every: 3
              send_first_at: 3
      - name: "Storage Temperature"
        id: zebus_storage_temperature
        device_class: "temperature"
        unit_of_measurement: "째C"
        state_class: "measurement"
        accuracy_decimals: 1
        internal: false
        message:
          command: 0xb511
          payload: [0x01]
          decode:
            position: 5
            bytes: 1
            divider: 2.0
        filters:
          - median:
              window_size: 5
              send_every: 3
              send_first_at: 3
      - name: "Displayed Room Temperature"
        id: zebus_disp_room_temperature
        message:
          destination: 0x10
          command: 0xb509
          payload: [0x0d, 0x3e, 0x00]
          decode:
            position: 0
            bytes: 2
            divider: 16.0
        device_class: "temperature"
        unit_of_measurement: "째C"
        state_class: "measurement"
        accuracy_decimals: 1
        internal: false
        filters:
          - median:
              window_size: 5
              send_every: 3
              send_first_at: 3
